export const testAry = [

   {name: '1. Якою командою в ОС Лінукс відкривають директорію?',
   a: {answer:'a. ls', id:'1-ls',},
   b: {answer:'cd', id:'1-cd',},
   c: {answer:'open', id:'1-open',},
   d: {answer:'mkdir', id:'1-mkdir',},
   i: {answer:'dir', id:'dir',},
   answerCorrect: 'cd',
},

{name: '2. Якою командою в ОС Лінукс можна повернутися у батьківську директорію?',
a: {answer:'cd ..', id:'2-cd',},
b: {answer:'ls -lh', id:'2-lh',},
c: {answer:'echo -e', id:'2-echo',},
d: {answer:'cat -A', id:'2-cat',},
i: {answer:'dir', id:'2-dir'},
answerCorrect: 'cd ..',
},


{name: '3. Як називається початок скрипта, написаного на мові сценаріїв bash, у вигляді #!/bin/bash?',
   a: {answer:'cowabunga', id:'3-cowabunga',},
   b: {answer:'fenshui', id:'3-fenshui',},
   c: {answer:'supercode', id:'3-supercode',},
   d: {answer:'bigbang', id:'3-bigbang',},
   i: {answer:'shebang', id:'shebang',},
   answerCorrect: 'shebang',
},

{name: '4. Якою командою в ОС Лінукс відкривають директорію?',
  a: {answer:'a. ls', id:'1-ls',},
  b: {answer:'cd', id:'1-cd',},
  c: {answer:'open', id:'1-open',},
  d: {answer:'mkdir', id:'1-mkdir',},
  i: {answer:'dir', id:'1-dir',},
answerCorrect: 'cd',
},

{name: '5. Якою командою в ОС Лінукс можна повернутися у батьківську директорію?',
  a: {answer:'cd ..', id:'2-cd',},
  b: {answer:'ls -lh', id:'2-lh',},
  c: {answer:'echo -e', id:'2-echo',},
  d: {answer:'cat -A', id:'2-cat',},
  i: {answer:'dir', id:'2-dir'},
answerCorrect: 'cd ..',
},

{name: '6. Як називається початок скрипта, написаного на мові сценаріїв bash, у вигляді #!/bin/bash?',
  a: {answer:'cowabunga', id:'3-cowabunga',},
  b: {answer:'fenshui', id:'3-fenshui',},
  c: {answer:'supercode', id:'3-supercode',},
  d: {answer:'bigbang', id:'3-bigbang',},
  i: {answer:'shebang', id:'shebang',},
answerCorrect: 'shebang',
},

{name: '7. Який буде результат застосування команди printf у командному рядку? printf echo %s \n hello', 
  a: {answer:'hello', id:'4-hello',},
  b: {answer:'echo hello', id:'4-echo hello',},
  c: {answer:'%s\n', id:'4-%s\n',},
  d: {answer:'echo hello\n', id:'4-echo hello\n',},
  i: {answer:'echo %s\n hello', id:'4-echo %s\n hello',}, 
answerCorrect: 'echo hello',
},

{name: '8. Якою комбінацією гарячих клавіш можна повернутися до початку командного рядка?',
  a: {answer:'backspace', id:'5-backspace',},
  b: {answer:'shift+backspace', id:'5-shift+backspace',},
  c: {answer:'ctrl+A', id:'5-ctrl+A',},
  d: {answer:'alt+tab', id:'5-ctrl+A',},
  i: {answer:'ctrl+0', id:'5-ctrl+0',},
answerCorrect: 'ctrl+A',
},

{name: '9. Що не належить до рівнів ініціалізації Linux у стилі systemd?',
  a: {answer:'user.target', id:'6-user.target',},
  b: {answer:'poweroff.target', id:'6-poweroff.target',},
  c: {answer:'graphical.target', id:'6-graphical.target',},
  d: {answer:'reboot.target', id:'6-reboot.target',},
  i: {answer:'rescue.target', id:'6-rescue.target',},
answerCorect: 'user.target',
},

{name: '10. Що не є файловою системою?',
  a: {answer:'NTFS', id:'7-NTFS',},
  b: {answer:'ext4', id:'7-ext4',},
  c: {answer:'FAT32', id:'7-FAT32',},
  d: {answer:'DISCFS', id:'7-DISCFS',},
  i: {answer:'SAMBA', id:'7-SAMBA',},
answerCorrect: 'DISCFS',
},

{name: '11. У якому файлі зберігаються паролі користувачів у зашифрованому вигляді?',
  a: {answer:'~/documents/secret', id:'8-~/documents/secret',},
  b: {answer:'/etc/passwd', id:'8-/etc/passwd',},
  c: {answer:'/var/log/auth.log', id:'8-/var/log/auth.log',},
  d: {answer:'/etc/shadow', id:'8-/etc/shadow',},
  i: {answer:'/proc/keys', id:'8-/proc/keys',},
answerCorrect: '/etc/shadow',
},

{name: '12. Яким символом підстановки (globbing) позначається будь-яка послідовність яких завгодно символів?',
  a: {answer:'&&', id:'&&',},
  b: {answer:'?', id:'9-?',},
  c: {answer:'#', id:'9-#',},
  d: {answer:'.', id:'9-.',},
  i: {answer:'*', id:'9-*',},
answerCorrect: '*',
},

]